version: '3'
services:
  my-service:
    image: back_image
    ports:
      - "8080:8080"
    environment:
      - CURRENT_ENVIRONMENT=development

  my-frontend:
    image: front_image
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://my-service:8080
